# Generated by Django 5.2.7 on 2025-10-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='driver_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Current latitude of the driver', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='driver_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Current longitude of the driver', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='is_started',
            field=models.BooleanField(default=False, help_text='Whether the driver has started this task'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text="When the driver's location was last updated", null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the driver started the task', null=True),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', help_text='Current status of the delivery task', max_length=20),
        ),
    ]
